/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.awt.Cursor;

/**
 *
 * @author rahen
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        panelMahasiswa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panelKrs = new javax.swing.JButton();
        panelDosen = new javax.swing.JButton();
        panelMataKuliah = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMahasiswa.setText("Data Mahasiswa");
        panelMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMahasiswaMouseClicked(evt);
            }
        });
        panelMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelMahasiswaActionPerformed(evt);
            }
        });

        jLabel1.setText("Aplikasi Pendataan Mahasiswa/Mahasiswi");

        panelKrs.setText("KRS");
        panelKrs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelKrsMouseClicked(evt);
            }
        });
        panelKrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelKrsActionPerformed(evt);
            }
        });

        panelDosen.setText("Data Dosen");
        panelDosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelDosenMouseClicked(evt);
            }
        });
        panelDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelDosenActionPerformed(evt);
            }
        });

        panelMataKuliah.setText("Mata Kuliah");
        panelMataKuliah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMataKuliahMouseClicked(evt);
            }
        });
        panelMataKuliah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelMataKuliahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelMataKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(panelKrs, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(477, Short.MAX_VALUE)
                    .addComponent(panelDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(70, 70, 70)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel1)
                .addGap(84, 84, 84)
                .addComponent(panelMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(panelMataKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelKrs, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(186, 186, 186)
                    .addComponent(panelDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(263, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelMahasiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelMahasiswaActionPerformed

    private void panelKrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelKrsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelKrsActionPerformed

    private void panelDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelDosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelDosenActionPerformed

    private void panelMataKuliahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelMataKuliahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelMataKuliahActionPerformed

    private void panelMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMahasiswaMouseClicked
 try {
        this.setVisible(false);
        new StudentForm(this).setVisible(true);
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Gagal membuka form mahasiswa: " + ex.getMessage());
        this.setVisible(true);
    }
    }//GEN-LAST:event_panelMahasiswaMouseClicked

    private void panelDosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDosenMouseClicked
        this.setVisible(false);
        new LecturerForm().setVisible(true);
    }//GEN-LAST:event_panelDosenMouseClicked

    private void panelMataKuliahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMataKuliahMouseClicked
        this.setVisible(false);
        new CourseForm().setVisible(true);
    }//GEN-LAST:event_panelMataKuliahMouseClicked

    private void panelKrsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelKrsMouseClicked
        this.setVisible(false);
        new KRSForm().setVisible(true);
    }//GEN-LAST:event_panelKrsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JButton panelDosen;
    private javax.swing.JButton panelKrs;
    private javax.swing.JButton panelMahasiswa;
    private javax.swing.JButton panelMataKuliah;
    // End of variables declaration//GEN-END:variables
}