/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.StudentController;
import controller.CourseController;
import controller.LecturerController;
import controller.KRSController;
import model.Student;
import model.Course;
import model.Lecturer;
import model.KRS;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author rahen
 */
public class KRSForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KRSForm.class.getName());

    /**
     * Creates new form KRSForm
     */
    public KRSForm() {
        initComponents();
        setupCombos();
        setupTable();
        loadData();
        clearForm();
    }
    
    private Dashboard dashboard;

    public KRSForm(Dashboard dashboard) {
    this();
    this.dashboard = dashboard;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jFrame1 = new javax.swing.JFrame();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        mahasiswaCombo1 = new javax.swing.JComboBox<>();
        mkCombo1 = new javax.swing.JComboBox<>();
        semesterCombo1 = new javax.swing.JComboBox<>();
        dosenCombo1 = new javax.swing.JComboBox<>();
        labelNim1 = new javax.swing.JLabel();
        labelMkSks1 = new javax.swing.JLabel();
        labelNidn1 = new javax.swing.JLabel();
        btnBatal1 = new javax.swing.JButton();
        btnHapus1 = new javax.swing.JButton();
        btnSimpan1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        sikapField1 = new javax.swing.JTextField();
        utsField1 = new javax.swing.JTextField();
        uasField1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        mahasiswaCombo = new javax.swing.JComboBox<>();
        mkCombo = new javax.swing.JComboBox<>();
        semesterCombo = new javax.swing.JComboBox<>();
        dosenCombo = new javax.swing.JComboBox<>();
        labelNim = new javax.swing.JLabel();
        labelMkSks = new javax.swing.JLabel();
        labelNidn = new javax.swing.JLabel();
        btnBatal = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        sikapField = new javax.swing.JTextField();
        utsField = new javax.swing.JTextField();
        uasField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        lblPage = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel10.setText("Nama Mahasiswa/Mahasiswi");

        jLabel11.setText("NIM Mahasiswa/Mahasiswi");

        jLabel12.setText("Code Matakuliah");

        jLabel13.setText("MK");

        jLabel14.setText("Semester");

        jLabel15.setText("Nama Dosen");

        jLabel16.setText("NIDN Dosen");

        mahasiswaCombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        mahasiswaCombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mahasiswaCombo1ActionPerformed(evt);
            }
        });

        mkCombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        mkCombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mkCombo1ActionPerformed(evt);
            }
        });

        semesterCombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        dosenCombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dosenCombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosenCombo1ActionPerformed(evt);
            }
        });

        labelNim1.setText("-");

        labelMkSks1.setText("-");

        labelNidn1.setText("-");

        btnBatal1.setText("BATALKAN");
        btnBatal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatal1ActionPerformed(evt);
            }
        });

        btnHapus1.setText("HAPUS");
        btnHapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapus1ActionPerformed(evt);
            }
        });

        btnSimpan1.setText("SIMPAN");
        btnSimpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpan1ActionPerformed(evt);
            }
        });

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(table1);

        sikapField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sikapField1ActionPerformed(evt);
            }
        });

        utsField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utsField1ActionPerformed(evt);
            }
        });

        uasField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uasField1ActionPerformed(evt);
            }
        });

        jLabel17.setText("NILAI");

        jLabel18.setText("Nilai Sikap");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(47, 47, 47))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(36, 36, 36)))
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNim1)
                            .addComponent(mahasiswaCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(184, 184, 184)))
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMkSks1)
                            .addComponent(mkCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jFrame1Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addGap(129, 129, 129)))
                            .addGroup(jFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(133, 133, 133)))
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNidn1)
                            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(semesterCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dosenCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 942, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jFrame1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(jFrame1Layout.createSequentialGroup()
                                .addComponent(sikapField1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(utsField1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(uasField1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBatal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHapus1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSimpan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(mahasiswaCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(labelNim1)
                    .addComponent(btnSimpan1))
                .addGap(18, 18, 18)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(mkCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatal1))
                .addGap(18, 18, 18)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(labelMkSks1)
                    .addComponent(btnHapus1))
                .addGap(19, 19, 19)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(semesterCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(dosenCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(labelNidn1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sikapField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(utsField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uasField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama Mahasiswa/Mahasiswi");

        jLabel2.setText("NIM Mahasiswa/Mahasiswi");

        jLabel3.setText("Code Matakuliah");

        jLabel4.setText("MK");

        jLabel5.setText("Semester");

        jLabel6.setText("Nama Dosen");

        jLabel7.setText("NIDN Dosen");

        mahasiswaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        mahasiswaCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mahasiswaComboActionPerformed(evt);
            }
        });

        mkCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        mkCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mkComboActionPerformed(evt);
            }
        });

        semesterCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        dosenCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dosenCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosenComboActionPerformed(evt);
            }
        });

        labelNim.setText("-");

        labelMkSks.setText("-");

        labelNidn.setText("-");

        btnBatal.setText("BATALKAN");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(table);

        sikapField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sikapFieldActionPerformed(evt);
            }
        });

        utsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utsFieldActionPerformed(evt);
            }
        });

        uasField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uasFieldActionPerformed(evt);
            }
        });

        jLabel8.setText("NILAI");

        jLabel9.setText("Nilai Sikap");

        jLabel19.setText("Nilai uts");

        jLabel20.setText("KRS Mahasiswa/Mahasiswi");

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        btnPrev.setText("Prev");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        lblPage.setText("Halaman 1 dari 1");

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        jLabel21.setText("Nilai uas");

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        jLabel22.setText("Cari NIM Mahasiswa/Mahasiswi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addGap(129, 129, 129)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelNidn)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(semesterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(dosenCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(56, 56, 56)
                                        .addComponent(btnCari))
                                    .addComponent(jLabel22)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel9)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(sikapField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(utsField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(uasField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel19)
                                            .addGap(41, 41, 41)
                                            .addComponent(jLabel21)
                                            .addGap(17, 17, 17)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(47, 47, 47))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(36, 36, 36)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelNim)
                                            .addComponent(mahasiswaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3))
                                        .addGap(107, 107, 107)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelMkSks)
                                            .addComponent(mkCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 942, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(323, 323, 323)
                                            .addComponent(btnPrev)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblPage)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnNext)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 341, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel20)
                        .addGap(378, 378, 378)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKembali)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnBatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(btnKembali))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(mahasiswaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelNim)
                    .addComponent(btnSimpan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(mkCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(labelMkSks)
                    .addComponent(btnHapus))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(semesterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dosenCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(labelNidn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel19)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sikapField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(utsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uasField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrev)
                    .addComponent(lblPage)
                    .addComponent(btnNext))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        clearForm();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        if (selectedId == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data dari tabel dulu.");
        return;
    }
    int confirm = JOptionPane.showConfirmDialog(this, "Hapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        if (krsController.delete(selectedId) == 1) {
            JOptionPane.showMessageDialog(this, "Data KRS berhasil dihapus.");
            loadData();
            clearForm();
        }
    }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
    if (studentList.isEmpty() || courseList.isEmpty() || lecturerList.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Data mahasiswa/matakuliah/dosen belum tersedia.");
        return;
    }
    int sikap, uts, uas;
    try {
        sikap = Integer.parseInt(sikapField.getText());
        uts = Integer.parseInt(utsField.getText());
        uas = Integer.parseInt(uasField.getText());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Nilai harus berupa angka.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    Student student = studentList.get(mahasiswaCombo.getSelectedIndex());
    Course course = courseList.get(mkCombo.getSelectedIndex());
    Lecturer lecturer = lecturerList.get(dosenCombo.getSelectedIndex());
    int semester = Integer.parseInt((String) semesterCombo.getSelectedItem());

    double score = (sikap + uts + uas) / 3.0;
    KRS tempKrs = new KRS(course, score);
    String grade = tempKrs.getGrade();

    int result;
    if (selectedId == -1) {
        result = krsController.create(student.getNim(), course.getId(), lecturer.getId(),
                semester, sikap, uts, uas, score, grade);
    } else {
        result = krsController.update(selectedId, student.getNim(), course.getId(), lecturer.getId(),
                semester, sikap, uts, uas, score, grade);
    }

    if (result == 1) {
        JOptionPane.showMessageDialog(this, "Data KRS berhasil disimpan.");
        loadData();
        clearForm();
    } else {
        JOptionPane.showMessageDialog(this, "Gagal menyimpan data.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void sikapFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sikapFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sikapFieldActionPerformed

    private void utsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_utsFieldActionPerformed

    private void uasFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uasFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uasFieldActionPerformed

    private void mahasiswaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mahasiswaComboActionPerformed
        updateMahasiswaLabel();
    }//GEN-LAST:event_mahasiswaComboActionPerformed

    private void mkComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mkComboActionPerformed
        updateMkLabel();
    }//GEN-LAST:event_mkComboActionPerformed

    private void dosenComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosenComboActionPerformed
        updateDosenLabel();
    }//GEN-LAST:event_dosenComboActionPerformed

    private void mahasiswaCombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mahasiswaCombo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mahasiswaCombo1ActionPerformed

    private void mkCombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mkCombo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mkCombo1ActionPerformed

    private void dosenCombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosenCombo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dosenCombo1ActionPerformed

    private void btnBatal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBatal1ActionPerformed

    private void btnHapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapus1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapus1ActionPerformed

    private void btnSimpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpan1ActionPerformed

    private void sikapField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sikapField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sikapField1ActionPerformed

    private void utsField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utsField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_utsField1ActionPerformed

    private void uasField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uasField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uasField1ActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
    if (dashboard != null) {
        dashboard.setVisible(true);
    } else {
        new Dashboard().setVisible(true);
    }
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if (currentPage < totalPages) { currentPage++; loadData(); }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        if (currentPage > 1) { currentPage--; loadData(); }
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
    searchKeyword = searchField.getText().trim();
    currentPage = 1;
    loadData();
    }//GEN-LAST:event_btnCariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new KRSForm().setVisible(true));
    }
    
private StudentController studentController = new StudentController();
private CourseController courseController = new CourseController();
private LecturerController lecturerController = new LecturerController();
private KRSController krsController = new KRSController();

private List<Student> studentList = new ArrayList<>();
private List<Course> courseList = new ArrayList<>();
private List<Lecturer> lecturerList = new ArrayList<>();
private DefaultTableModel tableModel;
private int selectedId = -1;
private int currentPage = 1;
private int totalPages = 1;
private final int PAGE_SIZE = 5;
private String searchKeyword = "";

private void setupCombos() {
    studentList = studentController.getStudent();
    mahasiswaCombo.removeAllItems();
    for (Student s : studentList) mahasiswaCombo.addItem(s.getName());

    courseList = courseController.getCourse();
    mkCombo.removeAllItems();
    for (Course c : courseList) mkCombo.addItem(c.getCourseName());

    lecturerList = lecturerController.getLecturer();
    dosenCombo.removeAllItems();
    for (Lecturer l : lecturerList) dosenCombo.addItem(l.getName());

    semesterCombo.removeAllItems();
    for (int i = 1; i <= 10; i++) semesterCombo.addItem(String.valueOf(i));
}

private void updateMahasiswaLabel() {
    int idx = mahasiswaCombo.getSelectedIndex();
    if (idx >= 0 && idx < studentList.size()) {
        Student s = studentList.get(idx);
        labelNim.setText(s.getNim() + " | " + s.getStudyProgram());
    }
}

private void updateMkLabel() {
    int idx = mkCombo.getSelectedIndex();
    if (idx >= 0 && idx < courseList.size()) {
        Course c = courseList.get(idx);
        labelMkSks.setText(c.getCode() + " (" + c.getSKS() + " SKS)");
    }
}

private void updateDosenLabel() {
    int idx = dosenCombo.getSelectedIndex();
    if (idx >= 0 && idx < lecturerList.size()) {
        Lecturer l = lecturerList.get(idx);
        labelNidn.setText(l.getNidn() + " | Pengampu: " + l.getExpertise());
    }
}
private void setupTable() {
    tableModel = new DefaultTableModel(
        new Object[]{"ID", "NIM", "Nama", "Matakuliah", "SKS", "Semester", "Nilai", "Dosen"}, 0) {
        @Override
        public boolean isCellEditable(int row, int column) { return false; }
    };
    table.setModel(tableModel);

    table.getSelectionModel().addListSelectionListener(e -> {
        int row = table.getSelectedRow();
        if (row >= 0) {
            selectedId = Integer.parseInt(tableModel.getValueAt(row, 0).toString());
            String nim = tableModel.getValueAt(row, 1).toString();
            String courseName = tableModel.getValueAt(row, 3).toString();
            String semester = tableModel.getValueAt(row, 5).toString();
            String dosenName = tableModel.getValueAt(row, 7).toString();

            selectByNim(nim);
            selectByCourseName(courseName);
            selectByDosenName(dosenName);
            semesterCombo.setSelectedItem(semester);
        }
    });
}

private void selectByNim(String nim) {
    for (int i = 0; i < studentList.size(); i++) {
        if (studentList.get(i).getNim().equals(nim)) { mahasiswaCombo.setSelectedIndex(i); break; }
    }
}

private void selectByCourseName(String name) {
    for (int i = 0; i < courseList.size(); i++) {
        if (courseList.get(i).getCourseName().equals(name)) { mkCombo.setSelectedIndex(i); break; }
    }
}

private void selectByDosenName(String name) {
    for (int i = 0; i < lecturerList.size(); i++) {
        if (lecturerList.get(i).getName().equals(name)) { dosenCombo.setSelectedIndex(i); break; }
    }
}

private void loadData() {
    int total;
    List<Object[]> list;
    int offset = (currentPage - 1) * PAGE_SIZE;

    if (searchKeyword.isEmpty()) {
        total = krsController.getTotalCount();
        list = krsController.getKRSPage(offset, PAGE_SIZE);
    } else {
        total = krsController.getSearchCount(searchKeyword);
        list = krsController.searchByNim(searchKeyword, offset, PAGE_SIZE);
    }

    totalPages = (int) Math.ceil((double) total / PAGE_SIZE);
    if (totalPages == 0) totalPages = 1;
    if (currentPage > totalPages) currentPage = totalPages;

    tableModel.setRowCount(0);
    for (Object[] row : list) tableModel.addRow(row);
    lblPage.setText("Halaman " + currentPage + " dari " + totalPages);
}
private void clearForm() {
    if (!studentList.isEmpty()) mahasiswaCombo.setSelectedIndex(0);
    if (!courseList.isEmpty()) mkCombo.setSelectedIndex(0);
    if (!lecturerList.isEmpty()) dosenCombo.setSelectedIndex(0);
    semesterCombo.setSelectedIndex(0);
    sikapField.setText("0");
    utsField.setText("0");
    uasField.setText("0");
    selectedId = -1;
    table.clearSelection();
    updateMahasiswaLabel();
    updateMkLabel();
    updateDosenLabel();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnBatal1;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHapus1;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnSimpan1;
    private javax.swing.JComboBox<String> dosenCombo;
    private javax.swing.JComboBox<String> dosenCombo1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelMkSks;
    private javax.swing.JLabel labelMkSks1;
    private javax.swing.JLabel labelNidn;
    private javax.swing.JLabel labelNidn1;
    private javax.swing.JLabel labelNim;
    private javax.swing.JLabel labelNim1;
    private javax.swing.JLabel lblPage;
    private javax.swing.JComboBox<String> mahasiswaCombo;
    private javax.swing.JComboBox<String> mahasiswaCombo1;
    private javax.swing.JComboBox<String> mkCombo;
    private javax.swing.JComboBox<String> mkCombo1;
    private javax.swing.JTextField searchField;
    private javax.swing.JComboBox<String> semesterCombo;
    private javax.swing.JComboBox<String> semesterCombo1;
    private javax.swing.JTextField sikapField;
    private javax.swing.JTextField sikapField1;
    private javax.swing.JTable table;
    private javax.swing.JTable table1;
    private javax.swing.JTextField uasField;
    private javax.swing.JTextField uasField1;
    private javax.swing.JTextField utsField;
    private javax.swing.JTextField utsField1;
    // End of variables declaration//GEN-END:variables
}